/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardBlock: typeof import('./src/components/CardBlock.vue')['default']
    'CardBlock.story': typeof import('./src/components/CardBlock.story.vue')['default']
    CardTitleBlock: typeof import('./src/components/CardTitleBlock.vue')['default']
    copy: typeof import('./src/components/VCardTitleBlock copy.vue')['default']
    VCard: typeof import('vuetify/components')['VCard']
    VCardSubtitle: typeof import('vuetify/components')['VCardSubtitle']
    VCardSubtitleBlock: typeof import('./src/components/VCardSubtitleBlock.vue')['default']
    VCardSubtTitleBlock: typeof import('vuetify/components')['VCardSubtTitleBlock']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCardTitleBlock: typeof import('./src/components/VCardTitleBlock.vue')['default']
    'VCardTitleBlock copy': typeof import('./src/components/VCardTitleBlock copy.vue')['default']
    'VCardTitleBlock.story': typeof import('./src/components/VCardTitleBlock.story.vue')['default']
    VContainer: typeof import('vuetify/components')['VContainer']
    VEditBlock: typeof import('./src/components/VEditBlock.vue')['default']
    VHover: typeof import('vuetify/components')['VHover']
    VIcon: typeof import('vuetify/components')['VIcon']
    VMain: typeof import('vuetify/components')['VMain']
    VTextField: typeof import('vuetify/components')['VTextField']
    VTextFieldBlock: typeof import('./src/components/VTextFieldBlock.vue')['default']
  }
}
